version: "2.3"
services:
  jupyterlab:
    build:
      context: .
    user: root
    ports:
      - "7777:8888"
    runtime: nvidia
    volumes:
      - "./notebooks:/notebooks"
    command: jupyter lab --allow-root --ip=0.0.0.0 --no-browser --port=8888 --NotebookApp.token=''
